#!/usr/bin/env bash
# Copy file from local to remote serve using ssh

if [ "$3" ]
then
    if [ "$4" ]
    then
	scp "$1" "$3"@"$2":"$4"
    else
	scp "$1" "$3@$2":~/
    fi
else
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi
