#!/usr/bin/env bash
# Install Nginx

sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
add="/^/\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n/"
sed -i "53s $add" /etc/nginx/sites-available/default
sudo service nginx restart
